name: Cleanup Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Remove Preview
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to push to gh-pages
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Remove preview directory
        run: |
          if [ -d "unsafe_preview/pr-${{ github.event.number }}" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git rm -rf "unsafe_preview/pr-${{ github.event.number }}"
            git commit -m "Remove preview for PR #${{ github.event.number }}"
            git push
          else
            echo "Preview directory does not exist, nothing to clean up"
          fi
