name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  check:
    name: Run Checks
    if: ${{ github.event.pull_request.draft == false && github.event.pull_request.state == 'open' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check
